title: Lebab
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Lebab is a tool which  takes an old JavaScript code and transpiles it
  into a modern code. It does the opposite of Babel.
baseurl: ""
url: "http://lebab.io"
twitter_username: lebab
github_username:  mohebifar
markdown: kramdown
